### ISSUE TITLE
JmsQueueSource does not implement Serizalizable correctly.

### ISSUE THREAD

**Issue by yoroto** [miwurster/flink-connector-jms#1]
Since it extends RichParallelSourceFunction, which implements the Serializable interface, JmsQueueSource should handle the serialization of its members. However, the type of connectionFactory, QueueConnectionFactory, does not implement Serializable, and there is not code to handle its serialization in JmsQueueSource. Therefore, when Flink later serializes JmsQueueSource, it could throw NotSerializableException on connectionFactory, if the implementation of QueueConnectionFactory didn't implement Serializable.

I understand that the IBM implementation of QueueConnectionFactory, JmsQueueConnectionFactory does implement Serializable, but here you cannot make the assumption that all the implementations of QueueConnectionFactory would do that, since it is not in its signature.

**Comment by miwurster** [comment]
As I remember, if a parent class already implements `Serializable` then child class doesn't need to implement it. So, as `AbstractRichFunction` already implements I think we are good to go...
